### ISSUE TITLE
Body Matrix Macro

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#41] opened 2017-05-01 21:19 UTC
The Body Matrix is what will be used for content of most content pages. The macro is [defined here](http://107.170.57.118/admin/settings/fields/edit/8).

Typical content page looks like this: 

![image](https://cloud.githubusercontent.com/assets/779882/25595318/512a59b8-2e92-11e7-8c7c-90bef0750e42.png)

**Comment by acolangelo** [comment] 2017-05-04 00:47
Closing as dupe of #47.

**Closed by acolangelo** 2017-05-04 00:47 UTC
